[options]
admin_passwd = ${ODOO_MASTER_PASSWORD}
db_name = arlet_odoo
proxy_mode = True
addons_path = /mnt/extra-addons,/usr/lib/python3/dist-packages/odoo/addons
data_dir = /var/lib/odoo
log_level = warn
workers = 2
limit_memory_hard = 2684354560
limit_memory_soft = 2147483648
limit_request = 8192
limit_time_cpu = 60
limit_time_real = 120